### ISSUE TITLE
Tests !

### ISSUE THREAD

**Issue by sadortun** [prelt65/preEnt#1]
Salut @prelt65,

Merci beaucoup de ta soumission ! 

Serais tu en mesure d'ajouter quelques nuit tests pour valider ta solution ? 

Par exemple, pour le problème 1, toutes les chaînes sont accepter.  Ainsi que les nombres négatifs et les floats.  J'aimerais voir quels sont les assomptions que tufaos a savoir ce qui est  inclu et exclu.

Merci,
Samuel

**Comment by prelt65** [comment]
Ok J'ai ajouté les test pour les deux exercises.

**Comment by sadortun** [comment]
Super! Merci!
