### ISSUE TITLE
Certains cas ne sont pas couvert

### ISSUE THREAD

**Issue by sadortun** [prelt65/preEnt#2]
Salut @prelt65 

Il y a quelques cas qui ne sont pas couvert lorsque les deux chiffres a permuter ne sont pas adjacent.

Voici quelques exemples:
- [x] 250  =>  502  ( au lieu de 520)
- [x] 580 => 805 ( au lieu de 850)
- [x] 13542
- [x] 136442

**Comment by prelt65** [comment]
Salut
Je viens de corriger et ajouter des unit test pour l'exercise 1
